package service

import (
	"errors"
	"fmt"
	"github.com/asmcos/requests"
	"github.com/go-olive/tv/model"
	"github.com/go-olive/tv/util"
	jsoniter "github.com/json-iterator/go"
	"net/http"
	"net/url"
	"regexp"
	"strings"
)

type DouyuYinService struct {
}

func init() {
	RegisterService("douyin", new(DouyuYinService))
}
func (s *DouyuYinService) GetPlayUrl(key string) (string, error) {
	return parseUrl(key)
}

func parseUrl(roomId string) (string, error) {
	u := "https://live.douyin.com/" + roomId
	req := &util.HttpRequest{
		URL:          u,
		Method:       "GET",
		ResponseData: *new(string),
		ContentType:  "application/json",
		Header: map[string]string{
			"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 Edg/94.0.992.38",
			"referer":    "https://live.douyin.com/",
			"cookie":     "__ac_nonce=0637dd0310078652b18cf; __ac_signature=_02B4Z6wo00f01uXLobQAAIDDG4fdhl-Cxbrl66UAANoc8WaYbvQ2dLhDmEqg3YxzQ6x0PyukJxHtArgSq9FGeq9LaS1H2iAG2VMYTh8WKgYIB6u2IX2uilRaIXhygB8THPmxOlQAKcJPNtKaa6;",
		},
	}
	var err error
	if err = req.Send(); err != nil {
		return "", err
	}
	resp := fmt.Sprint(req.ResponseData)
	splits := strings.Split(resp, "<script id=\"RENDER_DATA\" type=\"application/json\">")
	if len(splits) < 2 {
		return "", errors.New("找不到房间1")
	}
	resp = splits[1]
	resp = strings.Split(resp, "</script>")[0]
	resp, err = url.QueryUnescape(resp)
	if err != nil {
		return "", err
	}
	var autoGenerated model.DouyinAutoGenerated
	err = jsoniter.UnmarshalFromString(resp, &autoGenerated)
	if err != nil {
		return "", errors.New("找不到房间2")
	}
	if autoGenerated.App.InitialState.RoomStore.RoomInfo.Room.Status != 2 {
		return "", errors.New("直播间未开播2")
	}

	streamDataStr := autoGenerated.App.InitialState.RoomStore.RoomInfo.Room.StreamURL.LiveCoreSdkData.PullData.StreamData
	var streamData model.DouyinStreamData
	err = jsoniter.UnmarshalFromString(streamDataStr, &streamData)

	if streamData.Data.Origin.Main.Flv != "" {
		return streamData.Data.Origin.Main.Flv, nil

	} else {
		return "", errors.New("找不到房间1")
	}

}

func parseUrl2(room string) (string, error) {
	u := room
	url := "https://v.douyin.com/" + u + "/"
	id, _ := parseRoomId(url)

	roomUrl := "https://webcast.amemv.com/webcast/room/reflow/info/"
	p := requests.Params{
		"type_id": "0",
		"live_id": "1",
		"room_id": id,
		"app_id":  "1128",
		"X-Bogus": "1",
	}
	resp, _ := requests.Get(roomUrl, p, requests.Header{"authority": "webcast.amemv.com",
		"cookie": "_tea_utm_cache_1128={%22utm_source%22:%22copy%22%2C%22utm_medium%22:%22android%22%2C%22utm_campaign%22:%22client_share%22}",
	})
	json := jsoniter.ConfigCompatibleWithStandardLibrary
	durl := json.Get([]byte(resp.Text()), "data", "room", "stream_url", "rtmp_pull_url")

	url = durl.ToString()
	if url == "" {
		return "", errors.New("房间不存在")
	}
	return url, nil
}
func parseRoomId(url string) (string, error) {
	//获取roomId
	req, _ := http.NewRequest("HEAD", url, nil)
	// 比如说设置个token
	req.Header.Set("authority", "v.douyin.com")
	req.Header.Set("user-agent", "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1")
	client := &http.Client{
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}

	url = resp.Header.Get("Location")
	re := regexp.MustCompile(`\d{19}`)
	res := re.FindStringSubmatch(url)
	if len(res) > 0 {
		return res[0], nil
	} else {
		return "", errors.New("没用可以用的roomId")
	}
}
